<h1 class="text-center"><!-- tmpl_var name="text_awards_season1" --></h1>

<hr />

<h2 class="text-center"><!-- tmpl_var name="title" --></h3>

<div class="row">

  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_Award_Best_Production_Design.png" class="img-responsive center-block" alt="Asia Web Awards 2017 - Best Production Design" title="Asia Web Awards 2017 - Best Production Design" /></a></div>
  <div class="col-md-4"><a href="https://www.bnmwebfest.com"><img src="/images/BNMWF_2017_Award_Best_Fantasy.png" class="img-responsive center-block" alt="Baltimore Next Media Web Fest 2017 - Best Fantasy" title="Baltimore Next Media Web Fest 2017 - Best Fantasy" /></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_2017_Award_Direction.png" class="img-responsive center-block" alt="WGWC 2017 - Excellence - Direction" title="WGWC 2017 - Excellence - Direction" /></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_2017_Award_Costume_Design.png" class="img-responsive center-block" alt="WGWC 2017 - Excellence - Costume Design" title="WGWC 2017 - Excellence - Costume Design" /></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_2017_Award_Actor_Lead.png" class="img-responsive center-block" alt="WGWC 2017 - Exceptional Merit - Actor Lead" title="WGWC 2017 - Exceptional Merit - Actor Lead" /></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_2017_Award_Actor_Supporting.png" class="img-responsive center-block" alt="WGWC 2017 - Exceptional Merit - Actor Supporting" title="WGWC 2017 - Exceptional Merit - Actor Supporting" /></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_2017_Award_Merit_Direction.png" class="img-responsive center-block" alt="WGWC 2017 - Exceptional Merit - Direction" title="WGWC 2017 - Exceptional Merit - Direction" /></a></div>

</div>

<h2 class="text-center"><!-- tmpl_var name="text_awards_nominations" --></h2>

<div class="row">

  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelcomedy.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Comedy" title="Asia Web Awards 2017 - Best Comedy"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelcostume.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Costume Design" title="Asia Web Awards 2017 - Best Costume Design"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelproduction.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Production Design" title="Asia Web Awards 2017 - Best Production Design"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelsf.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Science Fiction" title="Asia Web Awards 2017 - Best Science Fiction"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelsfx.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Special Visual Effect" title="Asia Web Awards 2017 - Best Special Visual Effect"/></a></div>
  <div class="col-md-4"><a href="https://www.mnwebfest.com/"><img src="/images/MWF_2017_BEST_CINEMATOGRAPHY.png" class="img-responsive" alt="Minnesota WebFest 2017 - Best Cinematography" title="Minnesota WebFest 2017 - Best Cinematography"/></a></div>
  <div class="col-md-4"><a href="https://www.mnwebfest.com/"><img src="/images/MWF_2017_BEST_SCI-FI_FANTASY.png" class="img-responsive" alt="Minnesota WebFest 2017 - Best Sci-Fi Fantasy" title="Minnesota WebFest 2017 - Best Sci-Fi Fantasy"/></a></div>
  <div class="col-md-4"><a href="https://www.internationalonlinewebfest.com/"><img src="/images/IOWF_NOMINATION_2017BO.png" class="img-responsive" alt="International Online Web Fest 2017 - Best Original Soundtrack" title="International Online Web Fest 2017 - Best Original Soundtrack"/></a></div>
  <div class="col-md-4"><a href="https://www.internationalonlinewebfest.com/"><img src="/images/IOWF_NOMINATION_2017COSTUME.png" class="img-responsive" alt="International Online Web Fest 2017 - Best Costume Design" title="International Online Web Fest 2017 - Best Costume Design"/></a></div>
  <div class="col-md-4"><a href="https://www.internationalonlinewebfest.com/"><img src="/images/IOWF_NOMINATION_2017NEWCOMER.png" class="img-responsive" alt="International Online Web Fest 2017 - Best Newcomer Actor" title="International Online Web Fest 2017 - Best Newcomer Actor"/></a></div>
  <div class="col-md-4"><a href="http://fantasticplanetfilmfestival.com/"><img src="/images/Fantastic_Planet_2017_scifi.png" class="img-responsive" alt="Fantastic Planet Film Festival 2017 - Horror, Sci-Fi, Fantasy Film Festival" title="Fantastic Planet Film Festival 2017 - Horror, Sci-Fi, Fantasy Film Festival"/></a></div>

</div>

<h2 class="text-center"><!-- tmpl_var name="text_awards_selections" --></h2>

<div class="row">

  <div class="col-md-4"><a href="http://webseriesfestivalglobal.com/"><img src="/images/WSFG_2018_Official_Selection.png" class="img-responsive" alt="Web Series Festival Global 2018 - Official selection" title="Web Series Festival Global 2018 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://www.berlinscifi.com"><img src="/images/BSFF_official_selection_2017.png" class="img-responsive" alt="Berlin Sci-fi FilmFest 2017 - Official selection" title="Berlin Sci-fi FilmFest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="https://www.bnmwebfest.com/"><img src="/images/BNM_official_selection_2017.png" class="img-responsive" alt="BNM WebFest 2017 - Official selection" title="BNM WebFest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://www.bajawebfest.com/"><img src="/images/BajaWebFest_2017_OFFICIAL_SELECTION.png" class="img-responsive" alt="Baja Web Fest 2017 - Official selection" title="Baja Web Fest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://fantasticplanetfilmfestival.com/"><img src="/images/Fantastic_Planet_2017.png" class="img-responsive" alt="Fantastic Planet Film Festival 2017 - Official selection" title="Fantastic Planet Film Festival 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="https://www.romawebfest.it/"><img src="/images/RWF_2017.png" class="img-responsive" alt="Roma Web Fest 2017 - Official selection" title="Roma Web Fest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://soflowebfest.com/"><img src="/images/OFFICIALSELECTION-SOFLOWEBFEST-MIAMIFL2017.png" class="img-responsive" alt="SOFLOWEBFEST 2017 - Official selection" title="SOFLOWEBFEST 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://www.filmquestfest.com/"><img src="/images/logo_filmquest_2017.png" class="img-responsive" alt="FilmQuest 2017 - Official selection" title="FilmQuest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://sicilywebfest.com/"><img src="/images/logo_swf_2017.png" class="img-responsive" alt="Sicily Web Fest 2017 - Official selection" title="Sicily Web Fest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="https://www.internationalonlinewebfest.com/"><img src="/images/IOWF_OFFICIAL_SELECTION_2017.png" class="img-responsive" alt="International Online Web Fest 2017 - Official selection" title="International Online Web Fest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="https://www.mnwebfest.com/"><img src="/images/MWF_2017.png" class="img-responsive" alt="Minnesota WebFest 2017 - Official selection" title="Minnesota WebFest 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="http://wgwc1.com/"><img src="/images/WGWC_Official_Selection.png" class="img-responsive" alt="WGWC 2017 - Official selection" title="WGWC 2017 - Official selection"/></a></div>
  <div class="col-md-4"><a href="https://www.romewebawards.it/"><img src="/images/RWA_2018_Official_Selection.png" class="img-responsive" alt="Rome Web Awards 2018 - Official selection" title="Rome Web Awards 2018 - Official selection"/></a></div>

</div>

