<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<h3 class="text-center">2017</h3>

<a href="https://www.asiawebawards.com/"><img src="/images/asia_web_awards_2017_best_production_design.png" class="img-responsive center-block" alt="Asia Web Awards 2017 - Best Production Design" title="Asia Web Awards 2017 - Best Production Design" /></a>

<h2 class="text-center"><!-- tmpl_var name="text_awards_selections" --></h2>

<h3 class="text-center">2018</h3>

<h3 class="text-center">2017</h3>

<div class="row">

  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelcomedy.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Comedy" title="Asia Web Awards 2017 - Best Comedy"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelcostume.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Costume Design" title="Asia Web Awards 2017 - Best Costume Design"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelproduction.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Production Design" title="Asia Web Awards 2017 - Best Production Design"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelsf.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Science Fiction" title="Asia Web Awards 2017 - Best Science Fiction"/></a></div>
  <div class="col-md-4"><a href="https://www.asiawebawards.com/"><img src="/images/AWA2017_nomination_laurelsfx.png" class="img-responsive" alt="Asia Web Awards 2017 - Best Special Visual Effect" title="Asia Web Awards 2017 - Best Special Visual Effect"/></a></div>

</div>
