<p class="text-center">
    <a class="btn btn-default hvr-bounce-to-right" href="https://twitter.com/DonJon_Legacy"><i class="fa fa-twitter"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="https://www.facebook.com/donjonlegacy"><i class="fa fa-facebook"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="http://www.dailymotion.com/donjonlegacy"><i class="fa fa-video-camera"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="http://donjonlegacy.tumblr.com/"><i class="fa fa-tumblr"></i></a>
</p>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Recherche bénévoles</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Graphistes</li>
      <li>Influenceurs</li>
      <li>Partenaires</li>
      <li>Diffuseurs</li>
      <li>Attachés de presse</li>
      <li>Fans</li>
    </ul>
    <p class="text-center"><a href="/fr/contact.html">Contactez-nous</a></p>
  </div>
</div>
