<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Teignome Puppet</h3>
  </div>
  <div class="panel-body text-center">
    <iframe frameborder="0" height="360px" width="300px" src="http://fr.ulule.com/mascotte-donjon-legacy/widget.html" scrolling="no"></iframe>
  </div>
</div>

<p class="text-center">
    <a class="btn btn-default" href="https://twitter.com/DonJon_Legacy"><i class="fa fa-twitter"></i></a>
    <a class="btn btn-default" href="https://www.facebook.com/donjonlegacy"><i class="fa fa-facebook"></i></a>
    <a class="btn btn-default" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
    <a class="btn btn-default" href="http://donjonlegacy.tumblr.com/"><i class="fa fa-tumblr"></i></a>
    <a class="btn btn-default" href="https://www.instagram.com/donjonlegacy/"><i class="fa fa-instagram"></i></a>
</p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Guilhem - Le chevalier à la canne à pêche</h3>
  </div>
  <div class="panel-body text-center">
  <a href="http://www.publier-un-livre.com/fr/le-livre-en-papier/387-le-chevalier-a-la-canne-a-peche-l-antevers-1">
    <img src="/images/pub_chevalier_canne.jpg" class="img-responsive center-block" />
  </a>
  </div>
  <div class="panel-footer text-center" style="font-size:10pt;">
    Novel in French from creator of DJL (with Grumpy Gnome)<br />
    <i>Available in ebook everywhere or in paper on <a href="http://www.publier-un-livre.com/fr/le-livre-en-papier/387-le-chevalier-a-la-canne-a-peche-l-antevers-1">le livre en papier</a></i>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Guilhem - Rézo</h3>
  </div>
  <div class="panel-body text-center">
  <a href="https://www.amazon.fr/plante-verte-Guilhem/dp/2924550165">
    <img src="/images/pub_plante_verte.png" class="img-responsive" />
  </a>
  </div>
  <div class="panel-footer text-center" style="font-size:10pt;">
    First novel in French (humour/SF) from Guilhem, creator of DJL<br />
    <i>Available in ebook everywhere or in paper on <a href="https://www.amazon.fr/plante-verte-Guilhem/dp/2924550165">Amazon</a></i>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Wanted</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Influencers</li>
      <li>Partners</li>
      <li>Distributors</li>
    </ul>
  </div>
  <div class="panel-footer text-center">
    <a href="/en/contact.html">Contact us</a>
  </div>
</div>
