<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Volunteers wanted</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Designers</li>
      <li>Influencers</li>
      <li>Partners</li>
      <li>Distributors</li>
      <li>Press agents</li>
      <li>Fans</li>
    </ul>
    <p class="text-center"><a href="/en/contact.html">Contact us</a></p>
  </div>
</div>
