            <!-- Banner -->
                <section id="banner">
                    <div class="content">
                        <header>
                            <h2>DonJon Legacy</h2>
                            <p><tmpl_var name="text_home_banner" /></p>
                        </header>
                        <span class="image"><img src="/images/avatar_djl_square.jpg" alt="DJL" /></span>
                    </div>
                    <a href="#one" class="goto-next scrolly">Next</a>
                </section>
