<p class="text-center">
    <a class="btn btn-default hvr-bounce-to-right" href="https://twitter.com/DonJon_Legacy"><i class="fa fa-twitter"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="https://www.facebook.com/donjonlegacy"><i class="fa fa-facebook"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="http://www.dailymotion.com/donjonlegacy"><i class="fa fa-video-camera"></i></a>
    <a class="btn btn-default hvr-bounce-to-right" href="http://donjonlegacy.tumblr.com/"><i class="fa fa-tumblr"></i></a>
</p>

<div class="panel panel-info">
  <a href="https://www.amazon.fr/plante-verte-Guilhem/dp/2924550165">
    <img src="/images/pub1.jpg" class="img-responsive" />
  </a>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Volunteers wanted</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Influencers</li>
      <li>Partners</li>
      <li>Distributors</li>
      <li>Press agents</li>
      <li>Fans</li>
    </ul>
    <p class="text-center"><a href="/en/contact.html">Contact us</a></p>
  </div>
</div>
