<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Recherche bénévoles</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Graphistes</li>
      <li>Influenceurs</li>
      <li>Partenaires</li>
      <li>Diffuseurs</li>
      <li>Attachés de presse</li>
      <li>Fans</li>
    </ul>
    <p class="text-center"><a href="/fr/contact.html">Contactez-nous</a></p>
  </div>
</div>
