            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="text_contact_mail" --></h2>
                        </header>

                        <!-- Content -->
                            <section id="content">

                            <p><!-- tmpl_var name="text_contact_socialnetworks" --></p>
                            <ul>
                                <li><a href="https://www.facebook.com/donjonlegacy" target="_blank">Facebook</a></li>
                                <li><a href="https://ludosphere.fr/@onzecreation" target="_blank">Mastodon</a></li>
                                <li><a href="https://twitter.com/DonJon_Legacy" target="_blank">X / Twitter</a></li>
                            </ul>
                            </section>
                        </div>
                    </div>
