            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="title" --></h2>
                        </header>

                        <!-- Content -->
                            <section id="content">

                                <p><!-- tmpl_var name="text_credits_intro" --></p>

                                <div class="table-wrapper">
<table>
  <tr>
    <th><!-- tmpl_var name="text_credits_creator" --></th>
    <td>Guilhem <a href="https://www.facebook.com/Guilhem-53297726330/"><i class="fa fa-facebook"></i></a> <a href="https://twitter.com/Guilhem0"><i class="fa fa-twitter-square"></i></a> <a href="http://guilhem0.free.fr/"><i class="fa fa-globe"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_director" --></th>
    <td>Olivier Ziel</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_dungeon_master" --></th>
    <td>Sébastien Sera</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_beast_master" --></th>
    <td>Clément Oudot</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_stagehand" --></th>
    <td>Benjamin Dayras</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_demonist" --></th>
    <td>Julie Renard</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_grumpy_gnome" --></th>
    <td>Ionah Mélin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_plunderer" --></th>
    <td>Dimitri Leroy</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_intruder" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_dungeon_heart_voice" --></th>
    <td>Monsieur Phal <a href="https://www.facebook.com/Monsieur-Phal-124324084250556/"><i class="fa fa-facebook-official"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_stone_truth_voice" --></th>
    <td>Marcus <a href="https://www.facebook.com/Marcus-182459345935/"><i class="fa fa-facebook-official"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_assistant_director" --></th>
    <td>Arnaud Uhl</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_photography_director" --></th>
    <td>Manuel Leroueil</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_sound_engineer" --></th>
    <td>Lucas Rollin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_sound_recordist_ep3" --></th>
    <td>Stephen Le Cocq</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_sound_recordist_voice_over" --></th>
    <td>Sergio Escorcio</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_first_assistant_camera" --></th>
    <td>Florent Larriven</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_camera_operator_ep3" --></th>
    <td>Tiffany Sudre</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_electrician" --></th>
    <td>Mars Bais</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_costumier" --></th>
    <td>Aurélie Vorillon</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_makeup" --></th>
    <td>Ophélie Duchêne</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_makeup_ep3" --></th>
    <td>Alexandra Moulié</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_puppeteer" --></th>
    <td>Ionah Mélin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_costume_help" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_editors_motion_designers" --></th>
    <td>Nicolas Brasseur, Olivier Ziel</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_sound_mixer" --></th>
    <td>Axel Renault</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_credits" --></th>
    <td>Nicolas Brasseur (<!-- tmpl_var name="text_credits_motion_design" -->)<br />
    Lucas Rollin (<!-- tmpl_var name="text_credits_sound_design_mix" -->)
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_color_grading" --></th>
    <td>Alexandre Sadowsky</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_special_effects_3d" --></th>
    <td>Samy Tichadou</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_dragon_modeling" --></th>
    <td>CC BY - Blender Foundation - <a href="http://www.sintel.org">Sintel</a> - created by Pablo Vazquez</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_demon_modeling" --></th>
    <td>Cecoaliensa c/o Turbosquid</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_music_composer" --></th>
    <td>Antoine Cailliez</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_english_translator" --></th>
    <td>
      Sophie Guinez<br />
      Alexandra Carteron<br />
      Lyndy Davies
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_spanish_translator" --></th>
    <td>
      Geoffroy Scheid<br />
      Lisette Gironda Scheid
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_german_translator" --></th>
    <td>
      Justine Cailliez<br />
      Haldor Ortmann
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_italian_translator" --></th>
    <td>
      Michel-Ange Taïbi<br />
      Vanessa Bonaffini<br />
      Mina Sohet
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_graphic_designer" --></th>
    <td>Vincere Studio <a href="http://cargocollective.com/vincere"><i class="fa fa-globe"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_managing_help" --></th>
    <td>
      Hervé Alix<br />
      Anne Etienne<br />
      Jessica Lamaze<br />
      Teddy Langlois<br />
      Clotilde Leturque<br />
      Yohan Pannet<br />
      Michel-Ange Taibi<br />
      Ahlem Zardoumi<br />
      Catherine Homsy<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_decoration_help" --></th>
    <td>
      Aurélie Vorillon<br />
      Mathieu Moreaud<br />
      Bastien Didier<br />
      Ophélie Duchêne<br />
      Sébastien Sera<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_communication_help" --></th>
    <td>
      Bruno Krupa<br />
      Aurélie Watieaux<br />
      Nadège Dupuis<br />
      Vincent Dupuis (Valdarion)<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_special_thanks" --></th>
    <td>
      ARTE Studio (Pascal Sottovia, Jean Buono, Pascale Brahamsha, Laurent Lefèbvre, Virginie Lacoste)<br />
      Panalux<br />
      Puzzle Vidéos<br />
      Ville de Chalons-en-Champagne<br />
      Conseil Général de l’Aisne<br />
      Les Amis de Montcornet<br />
      La Compagnie du Crépuscule<br />
      Association Onze Création<br />
      Audrey Andrasi<br />
      Thomas Gayet<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_more_thanks" --></th>
    <td>
      Nicolas Guilloz<br />
      Lyndy Davies<br />
      Marc Canova<br />
      Juliette Louis<br />
      Sophie Bataillon<br />
      Morgan Lechat<br />
      Lucien Bachelin<br />
      Xavier Bataillon<br />
      Michel Jolyot<br />
      Jean-Gabriel Harter<br />
      Claude Mériaux<br />
      Clément Zanon<br />
      Effet de Steel<br />
      Le restaurant de Fère-en-Tardenois<br />
      Hoki Sushi<br />
      Le Comptoir de la Licorne<br />
      Amanda et Nadine<br />
      Aymeric<br />
      Cyril<br />
      Bruno Poli<br />
      Chams Chitou<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_locations" --></th>
    <td>
      Caves médiévales de Chalons-en-Champagne (France 51)<br />
      Château de Fère-en-Tardenois (France 02)<br />
      Château de Montcornet (France 08)<br />
      ARTE Studio (France 92)<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_webmaster" --></th>
    <td>Clément Oudot</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_webdesign_assistant" --></th>
    <td>Théo Gayet</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_webeditor" --></th>
    <td>Guilhem</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_designer" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
</table>
</div>
</section>
</div>
</div>
