<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<div class="alert alert-info hvr-grow-shadow">
  <!-- tmpl_var name="text_credits_intro" -->
</div>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_creator" --></th>
    <td>Guilhem <a href="https://www.facebook.com/Guilhem-53297726330/"><i class="fa fa-facebook-official"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_director" --></th>
    <td>Olivier Ziel</td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_main_producer" --></th>
    <td>Guilhem <a href="https://www.facebook.com/Guilhem-53297726330/"><i class="fa fa-facebook-official"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_producer" --></th>
    <td>Les Films du Chat Blanc</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_producer" --></th>
    <td>Onze Création</td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_dungeon_master" --></th>
    <td>Sébastien Sera</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_beast_master" --></th>
    <td>Clément Oudot</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_stagehand" --></th>
    <td>Benjamin Dayras</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_demonist" --></th>
    <td>Julie Douine</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_grumpy_gnome" --></th>
    <td>Ionah Mélin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_plunderer" --></th>
    <td>Dimitri Leroy</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_intruder" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_dungeon_heart_voice" --></th>
    <td></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_stone_truth_voice" --></th>
    <td></td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_assistant_director" --></th>
    <td>Arnaud Uhl</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_photography_director" --></th>
    <td>Manuel Leroueil</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_sound_engineer" --></th>
    <td>Lucas Rollin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_first_assistant_camera" --></th>
    <td>Florent Larrivien</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_assistant_camera" --></th>
    <td></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_electrician" --></th>
    <td>Mars Bais</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_costumier" --></th>
    <td>Aurélie Vorillon</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_makeup" --></th>
    <td>Ophélie Duchêne</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_motion_design" --></th>
    <td>Nicolas Brasseur</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_puppeteer" --></th>
    <td>Ionah Mélin</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_colour_grading" --></th>
    <td></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_credits" --></th>
    <td>Nicolas Brasseur</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_3dfx" --></th>
    <td></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_music_composer" --></th>
    <td>Antoine Cailliez</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_translator" --></th>
    <td>Sophie Guinez</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_costume_help" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_managing_help" --></th>
    <td>
      Hervé Alix<br />
      Anne Etienne<br />
      Jessica Lamaze<br />
      Teddy Langlois<br />
      Clotilde Leturque<br />
      Yohan Pannet<br />
      Michel-Ange Taibi<br />
      Ahlem Zardoumi<br />
      Cathy<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_decoration_help" --></th>
    <td>
      Aurélie Vorillon<br />
      Mathieu Moreaud<br />
      Bastien Didier<br />
      Ophélie Duchêne<br />
      Sébastien Sera<br />
    </td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_special_thanks" --></th>
    <td>
      Studio Arte<br />
      Puzzle Vidéos<br />
      Ville de Chalons-en-Champagne<br />
      Conseil Général de l’Aisne<br />
      Les Amis de Montcornet<br />
      La Compagnie du Crépuscule<br />
      Onze Création<br />
      Audrey Andrasi<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_more_thanks" --></th>
    <td>
      Nicolas Guilloz<br />
      Lyndy Davies<br />
      Marc Canova<br />
      Juliette Louis<br />
      Sophie Bataillon<br />
      Morgan Lechat<br />
      Lucien Bachelin<br />
      Xavier Bataillon<br />
      Michel Jolyot<br />
      Jean-Gabriel Harter<br />
      Claude Mériaux<br />
      Clément Zanon<br />
      Effet de Steel<br />
      Le restaurant de Fère-en-Tardenois<br />
      Resto jap<br />
      Brasserie <br />
      Amanda et Nadine<br />
      Aymeric<br />
      Cyril<br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_locations" --></th>
    <td>
      Caves médiévales de Chalons-en-Champagne (France 51)<br />
      Château de Fère-en-Tardenois (France 02)<br />
      Château de Montcornet (France 08)<br />
    </td>
  </tr>
</table>

<table class="credits table table-striped">
  <tr>
    <th><!-- tmpl_var name="text_credits_webmaster" --></th>
    <td>Clément Oudot</td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_webeditor" --></th>
    <td>Guilhem <a href="https://www.facebook.com/Guilhem-53297726330/"><i class="fa fa-facebook-official"></i></a></td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_graphic_artist" --></th>
    <td>
      Florent Brasseur<br />
      Guilhem <a href="https://www.facebook.com/Guilhem-53297726330/"><i class="fa fa-facebook-official"></i></a><br />
    </td>
  </tr>
  <tr>
    <th><!-- tmpl_var name="text_credits_designer" --></th>
    <td>Thomas Vanicatte</td>
  </tr>
</table>
