            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="text_dungeon_map_title" --></h2>
                        </header>
                        
                        <!-- Content -->
                            <section id="content">

                                <p><!-- tmpl_var name="text_dungeon_map_description" --></p>
                                <div class="align-center">
                                    <img src="/images/carte.jpg" alt="<!-- tmpl_var name="text_dungeon_map_title" -->" usemap="#Map" class="image" />
                                </div>

  <map name="Map" id="Map">
    <area alt="<!-- tmpl_var name="text_dungeon_ruins_title" -->" title="<!-- tmpl_var name="text_dungeon_ruins_title" -->" href="#ruins" shape="poly" coords="12,15,10,173,250,86,217,1" />
    <area alt="<!-- tmpl_var name="text_dungeon_hall_title" -->" title="<!-- tmpl_var name="text_dungeon_hall_title" -->" href="#hall" shape="poly" coords="123,149,194,241,299,172,246,94" />
    <area alt="<!-- tmpl_var name="text_dungeon_cave_title" -->" title="<!-- tmpl_var name="text_dungeon_cave_title" -->" href="#cave" shape="poly" coords="316,98,402,159,523,91,437,27" />
    <area alt="<!-- tmpl_var name="text_dungeon_summoning_title" -->" title="<!-- tmpl_var name="text_dungeon_summoning_title" -->" href="#summoning" shape="poly" coords="434,252,510,206,592,254,559,324" />
    <area alt="<!-- tmpl_var name="text_dungeon_heart_title" -->" title="<!-- tmpl_var name="text_dungeon_heart_title" -->" href="#heart" shape="poly" coords="488,338,448,360,507,395,538,365" />
    <area alt="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" title="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" href="#masterroom" shape="poly" coords="501,398,480,419,516,434,538,410" />
  </map>



    <h2 id="ruins"><!-- tmpl_var name="text_dungeon_ruins_title" --></h2>

    <p>
        <span class="image left"><img src="/images/ruines.jpg" alt="<!-- tmpl_var name="text_dungeon_ruins_title" -->" /></span>
        <!-- tmpl_var name="text_dungeon_ruins_description" -->
    </p>


    <h2 id="heart"><!-- tmpl_var name="text_dungeon_heart_title" --></h2>

    <p>
      <span class="image right"><img src="/images/coeur.png" alt="<!-- tmpl_var name="text_dungeon_heart_title" -->" /></span>
      <!-- tmpl_var name="text_dungeon_heart_description" -->
    </p>

    <h2 id="masterroom"><!-- tmpl_var name="text_dungeon_masterroom_title" --></h2>

    <p>
      <span class="image left"><img src="/images/chambre.jpg" alt="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" /></span>
      <!-- tmpl_var name="text_dungeon_masterroom_description" -->
    </p>

    <h2 id="hall"><!-- tmpl_var name="text_dungeon_hall_title" --></h2>

    <p>
      <span class="image right"><img src="/images/garde.jpg" alt="<!-- tmpl_var name="text_dungeon_hall_title" -->" /></span>
      <!-- tmpl_var name="text_dungeon_hall_description" -->
    </p>

    <h2 id="summoning"><!-- tmpl_var name="text_dungeon_summoning_title" --></h2>

    <p>
      <span class="image left"><img src="/images/invocations.png" alt="<!-- tmpl_var name="text_dungeon_summoning_title" -->" /></span>
      <!-- tmpl_var name="text_dungeon_summoning_description" -->
    </p>

    <h2 id="cave"><!-- tmpl_var name="text_dungeon_cave_title" --></h2>

    <p>
      <span class="image right"><img src="/images/cave.png" alt="<!-- tmpl_var name="text_dungeon_cave_title" -->" /></span>
      <!-- tmpl_var name="text_dungeon_cave_description" -->
    </p>

    <h2></h2>

    </section>

  </div>

</div>
