<div class="text-center">

  <h1><!-- tmpl_var name="text_dungeon_map_title" --></h1>

  <hr />
  <a name="map"></a>

  <img src="/images/carte.jpg" alt="<!-- tmpl_var name="text_dungeon_map_title" -->" usemap="#Map" class="img-thumbnail hidden-xs" />
  <img src="/images/carte.jpg" alt="<!-- tmpl_var name="text_dungeon_map_title" -->" class="img-responsive hidden-sm hidden-md hidden-lg" />

  <map name="Map" id="Map">
    <area alt="<!-- tmpl_var name="text_dungeon_ruins_title" -->" title="<!-- tmpl_var name="text_dungeon_ruins_title" -->" href="#ruins" shape="poly" coords="12,15,10,173,250,86,217,1" />
    <area alt="<!-- tmpl_var name="text_dungeon_hall_title" -->" title="<!-- tmpl_var name="text_dungeon_hall_title" -->" href="#hall" shape="poly" coords="123,149,194,241,299,172,246,94" />
    <area alt="<!-- tmpl_var name="text_dungeon_cave_title" -->" title="<!-- tmpl_var name="text_dungeon_cave_title" -->" href="#cave" shape="poly" coords="316,98,402,159,523,91,437,27" />
    <area alt="<!-- tmpl_var name="text_dungeon_summoning_title" -->" title="<!-- tmpl_var name="text_dungeon_summoning_title" -->" href="#summoning" shape="poly" coords="434,252,510,206,592,254,559,324" />
    <area alt="<!-- tmpl_var name="text_dungeon_heart_title" -->" title="<!-- tmpl_var name="text_dungeon_heart_title" -->" href="#heart" shape="poly" coords="470,307,414,359,499,424,569,370" />
    <area alt="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" title="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" href="#masterroom" shape="poly" coords="167,318,255,273,311,312,250,390" />
  </map>

  <hr />

  <p class="dungeon_description">
    <!-- tmpl_var name="text_dungeon_map_description" -->
  </p>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_ruins_title" --></h2>
  <a name="ruins"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/ruines.jpg" alt="<!-- tmpl_var name="text_dungeon_ruins_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_ruins_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_heart_title" --></h2>
  <a name="heart"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/coeur.png" alt="<!-- tmpl_var name="text_dungeon_heart_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_heart_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_masterroom_title" --></h2>
  <a name="masterromm"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/chambre.jpg" alt="<!-- tmpl_var name="text_dungeon_masterroom_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_masterroom_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_hall_title" --></h2>
  <a name="hall"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/garde.jpg" alt="<!-- tmpl_var name="text_dungeon_hall_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_hall_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_summoning_title" --></h2>
  <a name="summoning"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/invocations.png" alt="<!-- tmpl_var name="text_dungeon_summoning_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_summoning_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

  <hr />

  <h2><!-- tmpl_var name="text_dungeon_cave_title" --></h2>
  <a name="cave"></a>

  <div class="row">
    <div class="col-sm-4 col-md-6">
      <img src="/images/cave.png" alt="<!-- tmpl_var name="text_dungeon_cave_title" -->" class="img-thumbnail img-responsive" />
    </div>
    <div class="col-sm-8 col-md-6">
      <p class="text-left"><!-- tmpl_var name="text_dungeon_cave_description" --></p>
    </div>
  </div>

  <a href="#map" class="btn btn-default"><!-- tmpl_var name="text_dungeon_backtomap" --></a>

</div>
