            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="title" --></h2>
                        </header>

                        <!-- Content -->
                            <section id="content">

                            <div>
                            <p class="align-center"><!-- tmpl_var name="text_events_intro" --></p>

                            <div class="row">

                            <div class="col-4 col-12-xsmall">
                            <h2>2025</h2>
                            <ul>
                            <li>Salon Fantastique de Paris</li>
                            </ul>
                            </div>

                            <div class="col-4 col-12-xsmall">
                            <h2>2024</h2>
                            <ul>
                            <li>Japan Expo Paris</li>
                            <li>Salon Fantastique de Paris</li>
                            </ul>
                            </div>

                            <div class="col-4 col-12-xsmall">
                            <h2>2023</h2>
                            <ul>
                            <li>Japan Expo Paris</li>
                            <li>Salon Fantastique de Paris</li>
                            <li>Avant-Première aux Caves St-Sabin (Paris)</li>
                            <li>Avant-Première au Hasard Ludique</li>
                            </ul>
                            </div>

                            </div>

                            <div class="row">

                            <div class="col-4 col-12-xsmall">
                            <h2>2019</h2>
                            <ul>
                            <li>Colmar Esport Show 2019</li>
                            <li>Poitiers Geek Festival 2019</li>
                            <li>Japan Tours Festival 2019</li>
                            <li>Geek Days Rennes 2019</li>
                            <li>Geek Days Lilles 2019</li>
                            <li>Japan Expo Paris 2019</li>
                            </ul>
                            </div>

                            <div class="col-4 col-12-xsmall">
                            <h2>2018</h2>
                            <ul>
                            <li>Les Joutes du Téméraire 2018 (Nancy)</li>
                            <li>Salon Fantastique de Paris 2018</li>
                            <li>MetzTorii 2018</li>
                            <li>World of Geek 2018 (Mouscron)</li>
                            <li>Geek Days 2018 (Lilles)</li>
                            <li>Geek Days 2018 (Rouen)</li>
                            <li>Geek Days 2018 (Rennes)</li>
                            <li>Carolo Game Show 2018 (Charleville-Mézières)</li>
                            <li>Japan Expo Paris 2018</li>
                            <li>Cidre et Dragon 2018 (Merville) </li>
                            <li>Salon Fantastique de Paris Winter 2018</li>
                            <li>Game in Reims 2018</li>
                            <li>Toulouse Game Show 2018</li>
                            </ul>
                            </div>

                            <div class="col-4 col-12-xsmall">
                            <h2>2017</h2>
                            <ul>
                            <li>Les Joutes du Téméraire 2017 (Nancy)</li>
                            <li>Trolls et Légendes 2017 (Mons)</li>
                            <li>Salon Fantastique de Paris 2017</li>
                            <li>Fêtes Johanniques de Reims 2017</li>
                            <li>Geek Touch & Haru Japan 2017 (Lyon)</li>
                            <li>Nice Fiction 2017</li>
                            <li>Salon du Livre de Fismes 2017</li>
                            <li>Geek Days 2017 (Lilles)</li>
                            <li>Bordeaux Geek Festival 2017</li>
                            <li>Japan Expo Paris 2017</li>
                            <li>Dormantastique 2017 (Dormans)</li>
                            <li>Game in Reims 2017</li>
                            </ul>
                            </div>

                            </div>
                            </div>

                            </section>
                            </div>
                            </div>
