<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<div class="alert alert-info hvr-grow-shadow">
  <!-- tmpl_var name="text_friends_intro" -->
</div>

<div class="row text-center">

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_webseries" --></h2>
    <p><a href="https://www.facebook.com/DonjonDeNaheulbeukSerieTv/posts/995069383901514?fref=nf">Donjon de Naheulbeuk</a></p>
    <p><a href="https://twitter.com/ZombieOrpheus/status/704734123932299264">Zombie Orpheus</a><br />(Journey Quest / The Gamers / Darkest Dungeon)</p>
    <p><a href="https://twitter.com/rentheseries/status/705717574647025664">Ren</a></p>
    <p><a href="https://twitter.com/onehitdieseries/status/704308676413124609">One Hit Die</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_press" --></h2>
    <p><a href="http://wp.me/p5pSxm-1cP">La Gazette du Geek</a></p>
    <p><a href="https://www.facebook.com/GeeKroniques/posts/987892187968694?fref=nf">Geekroniques</a></p>
    <p><a href="https://www.facebook.com/culturegeek/posts/1320855914596858?fref=nf">Culture Geek</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_forums" --></h2>
    <p><a href="http://forum.geekzone.fr/t/copinage-donjon-legacy/57527/23">GeekZone</a></p>
    <p><a href="http://www.gamekult.com/forum/topic-webserie-donjon-legacy-885259n.html">GameKult</a></p>
    <p><a href="http://www.jeuxvideo.com/forums/42-51-46265749-1-0-1-0-dojon-legacy-une-nouvelle-webserie-de-bad-fantasy-bien-barree.htm">Jeuxvideo.com</a></p>
    <p><a href="http://www.entre-geeks.com/forum/message/communaute/projet-des-membres/donjon-legacy-a-very-bad-fantasy-webseries">Entre Geek</a></p>
    <p><a href="http://www.koreus.com/modules/newbb/topic150549.html">Koreus</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_facegroups" --></h2>
    <p><a href="https://www.facebook.com/groups/EverythingSciFi.and.Fantasy/search/?query=donjon%20legacy">Everything Sci Fi and Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/1398822120358227/search/?query=donjon%20legacy">Heroic Fantasy et fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/heroicfantasy/search/?query=donjon%20legacy">Heroic Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/187614501677/search/?query=donjon%20legacy">Fan de Héroïc Fantasy et de fantastique</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_webbroadcasters" --></h2>
    <p><a href="http://www.reddit.com/r/Fantasy/comments/489kqx/teaser_of_donjon_legacy_project_a_funny_bad/">Reddit /fantasy</a></p>
  </div>

</div>
