<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<div class="alert alert-info hvr-trim">
  <!-- tmpl_var name="text_friends_intro" -->
</div>

<div class="row text-center">

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_webseries" --></h2>
    <p><a href="https://www.facebook.com/DonjonDeNaheulbeukSerieTv/posts/995069383901514?fref=nf">Donjon de Naheulbeuk</a></p>
    <p><a href="https://twitter.com/ZombieOrpheus/status/704734123932299264">Zombie Orpheus</a><br />(Journey Quest / The Gamers / Darkest Dungeon)</p>
    <p><a href="https://twitter.com/rentheseries/status/705717574647025664">Ren</a></p>
    <p><a href="https://twitter.com/onehitdieseries/status/704308676413124609">One Hit Die</a></p>
    <p><a href="https://www.facebook.com/Super-Raccord-147352751959836/">Super Raccord</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_press" --></h2>
    <p><a href="http://wp.me/p5pSxm-1cP">La Gazette du Geek</a></p>
    <p><a href="https://www.facebook.com/GeeKroniques/posts/987892187968694?fref=nf">Geekroniques</a></p>
    <p><a href="https://www.facebook.com/culturegeek/posts/1320855914596858?fref=nf">Culture Geek</a></p>
    <p><a href="http://www.syfantasy.fr/22265-Decouvrez_DonJon_Legacy_la_webserie_francaise_de_Bad_Fantasy">SyFantasy.fr</a></p>
    <p><a href="http://www.actusf.com/spip/breve-18277.html">Actu SF</a></p>
    <p><a href="http://allgeekuniverse.com/2016/03/09/donjon-legacy-la-web-serie-made-in-france/">All Geek Universe</a></p>
    <p><a href="http://www.bibou.org/donjon/">Les Murmures du Donjon</a></p>
    <p><a href="https://www.facebook.com/Fiers-dêtre-GEEK-194379330585368/">Fiers d'être geek</a></p>
    <p><a href="Dol Celeb">Dol Celeb</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_forums" --></h2>
    <p><a href="http://forum.geekzone.fr/t/copinage-donjon-legacy/57527/23">GeekZone</a></p>
    <p><a href="http://www.gamekult.com/forum/topic-webserie-donjon-legacy-885259n.html">GameKult</a></p>
    <p><a href="http://www.jeuxvideo.com/forums/42-51-46265749-1-0-1-0-dojon-legacy-une-nouvelle-webserie-de-bad-fantasy-bien-barree.htm">Jeuxvideo.com</a></p>
    <p><a href="http://www.entre-geeks.com/forum/message/communaute/projet-des-membres/donjon-legacy-a-very-bad-fantasy-webseries">Entre Geek</a></p>
    <p><a href="http://www.koreus.com/modules/newbb/topic150549.html">Koreus</a></p>
    <p><a href="http://libr-fantasymania.lebonforum.com/">Libr' FantasYmaniA</a></p>
    <p><a href="http://www.chemins-khatovar.com/forum/viewtopic.php?f=47&t=7184&sid=fcd4853729ba0ccd9d3acd1757d9a23d">Les Chemins de Khatovar</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_facegroups" --></h2>
    <p><a href="https://www.facebook.com/groups/EverythingSciFi.and.Fantasy/search/?query=donjon%20legacy">Everything Sci Fi and Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/1398822120358227/search/?query=donjon%20legacy">Heroic Fantasy et fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/heroicfantasy/search/?query=donjon%20legacy">Heroic Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/187614501677/search/?query=donjon%20legacy">Fan de Héroïc Fantasy et de fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/1488978857993787/?ref=browser">Fantasy et Science-fiction</a></p>
    <p><a href="https://www.facebook.com/groups/127028880783313/?ref=browser">Science-Fiction-fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/273096772740787/">Séries fantastiques et de science fiction</a></p>
    <p><a href="https://www.facebook.com/groups/205907599559799/">Monde féérique, médiéval et fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/6550919441">Fantasy.fr</a></p>
    <p><a href="https://www.facebook.com/groups/457416327679264">Trolls, Elfes, Lutins, Sorcières, Magiciens, Fauconniers et autres fééries</a></p>
    <p><a href="https://www.facebook.com/groups/Imaginaire2013">Terres de légendes, de fantasy et de l'imaginaire</a></p>
    <p><a href="https://www.facebook.com/groups/noobfans/permalink/1020252138062672/?comment_id=1027556767332209&notif_t=group_comment&notif_id=1460861226151967">NOOB & Co</a></p>
  </div>

  <div class="col-sm-6">
    <h2><!-- tmpl_var name="text_friends_title_webbroadcasters" --></h2>
    <p><a href="http://www.reddit.com/r/Fantasy/comments/489kqx/teaser_of_donjon_legacy_project_a_funny_bad/">Reddit /fantasy</a></p>
  </div>

</div>
