            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="title" --></h2>
                        </header>

                        <!-- Content -->
                            <section id="content">

                                <div class="align-center">

                                
                                <p><!-- tmpl_var name="text_friends_guests" --></p>
                                <p><img src="/images/guests-donjon-legacy.png" class="img-responsive img-thumbnail" /></p>
                                <p><i>Gastronogeek, Brigitte Lecordier, Baptiste Lecaplain, Davy Mourier, Frédéric Zolfanelli, Monsieur Phal, Marcus, Linguisticae, Moustafa Benaibout, Lucien Maine, Bob Lennon, Sébastien Mortamet</i></p>

                                <p><!-- tmpl_var name="text_friends_intro" --></p>
                                <p><a href="/images/cairn-djl.png" alt="Cairn DJL"><img src="/images/cairn-djl_600px.png" class="img-responsive img-thumbnail" /></a></p>

<div class="row">

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_webseries" --></h2>
    <p><a href="https://www.facebook.com/DonjonDeNaheulbeukSerieTv/posts/995069383901514?fref=nf">Donjon de Naheulbeuk</a></p>
    <p><a href="https://twitter.com/ZombieOrpheus/status/704734123932299264">Zombie Orpheus</a><br />(Journey Quest / The Gamers / Darkest Dungeon)</p>
    <p><a href="https://twitter.com/rentheseries/status/705717574647025664">Ren</a></p>
    <p><a href="https://twitter.com/onehitdieseries/status/704308676413124609">One Hit Die</a></p>
    <p><a href="https://www.facebook.com/Super-Raccord-147352751959836/">Super Raccord</a></p>
    <p><a href="https://www.facebook.com/Marcus-182459345935/">Marcus</a></p>
    <p><a href="https://www.facebook.com/Monsieur-Phal-124324084250556/">Monsieur Phal</a></p>
    <p><a href="https://www.duam-laserie.com/">DUAM</a></p>
    <p><a href="https://www.youtube.com/channel/UCwGeqKdAGQ_FQp3vftZ5abw?feature=plcp">Bruciare violini</a></p>
    <p><a href="http://lesseigneursdoutremonde.com/">Les Seigneurs d'Outre Monde</a></p>
    <p><a href="https://www.comptinesbarbares.com/">Comptines Barbares</a></p>
    <p><a href="https://www.youtube.com/watch?v=4JdALmf8rto">Anthox Collaboy</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_interviews" --></h2>
    <p><a href="https://www.facebook.com/petitpointgeek/videos/1480637798661615/">Petit Point Geek - 1</a></p>
    <p><a href="https://www.facebook.com/petitpointgeek/videos/1587049374687123/">Petit Point Geek - 2</a></p>
    <p><a href="https://www.youtube.com/watch?v=JrO8sD0miH0&t">Geeks By Girls - 1</a></p>
    <p><a href="https://www.youtube.com/watch?v=ELRShPNPvH0">Geeks By Girls - 2</a></p>
    <p><a href="https://www.youtube.com/watch?v=iUotqvISFPM">Le Songeorium</a></p>
    <p><a href="https://www.youtube.com/watch?v=h_M6UvpvW_k">Xavier Mateos</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_press" --></h2>
    <p><a href="http://wp.me/p5pSxm-1cP">La Gazette du Geek</a></p>
    <p><a href="https://www.facebook.com/GeeKroniques/posts/987892187968694?fref=nf">Geekroniques</a></p>
    <p><a href="https://www.facebook.com/culturegeek/posts/1320855914596858?fref=nf">Culture Geek</a></p>
    <p><a href="http://www.syfantasy.fr/22265-Decouvrez_DonJon_Legacy_la_webserie_francaise_de_Bad_Fantasy">SyFantasy.fr</a></p>
    <p><a href="http://www.actusf.com/spip/breve-18277.html">Actu SF</a></p>
    <p><a href="http://allgeekuniverse.com/2016/03/09/donjon-legacy-la-web-serie-made-in-france/">All Geek Universe</a></p>
    <p><a href="http://www.bibou.org/donjon/">Les Murmures du Donjon</a></p>
    <p><a href="https://www.facebook.com/Fiers-dêtre-GEEK-194379330585368/">Fiers d'être geek</a></p>
    <p><a href="https://www.dol-celeb.com/">Dol Celeb</a></p>
    <p><a href="http://www.g33kmania.com/donjon-legacy-webserie-de-bad-fantasy-made-in-france/">G33kMania</a></p>
    <p><a href="http://galaxy-geek.com/site/">Galaxy Geek</a></p>
    <p><a href="https://game-guide.fr/217422-donjon-legacy-la-webserie-qui-met-les-mechants-a-lhonneur/">Game Guide</a></p>
    <p><a href="https://www.geeksbygirls.com/donjon-legacy/">Geeks By Girls</a></p>
    <p><a href="http://www.lunion.fr/50668/article/2017-09-20/une-webserie-tournee-dans-les-caves-de-chalons">L'Union - 1</a></p>
    <p><a href="http://www.lunion.fr/61300/article/2017-11-20/une-webserie-remoise-primee-en-coree">L'Union - 2</a></p>
    <p><a href="https://libertadifrequenza.it/attualit%C3%A0-homepage/31-eventi-e-cultura-attualit%C3%A0/392-donjon-legacy-la-web-serie-fantasy-francese-ispirata-ai-giochi-di-ruolo.html">Libertà di Frequenza</a></p>
    <p><a href="http://pausegeek.fr/articles/383-compte-rendu-du-japan-touch-harugeek-touch-2017.geek">Pause Geek</a></p>
    <p><a href="http://www.maxoe.com/kissa/japon-dossiers/focus-evenement/japan-touch-haru-geek-touch-excellente-edition-2017/">MaXoE</a></p>
    <p><a href="http://www.leparisien.fr/culture-loisirs/sortir-region-parisienne/sortir-a-paris-bienvenue-dans-un-monde-fantastique-02-11-2017-7369152.php">Le Parisien</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_forums" --></h2>
    <p><a href="http://forum.geekzone.fr/t/copinage-donjon-legacy/57527/23">GeekZone</a></p>
    <p><a href="http://www.gamekult.com/forum/topic-webserie-donjon-legacy-885259n.html">GameKult</a></p>
    <p><a href="http://www.jeuxvideo.com/forums/42-51-46265749-1-0-1-0-dojon-legacy-une-nouvelle-webserie-de-bad-fantasy-bien-barree.htm">Jeuxvideo.com</a></p>
    <p><a href="http://www.entre-geeks.com/forum/message/communaute/projet-des-membres/donjon-legacy-a-very-bad-fantasy-webseries">Entre Geek</a></p>
    <p><a href="http://www.koreus.com/modules/newbb/topic150549.html">Koreus</a></p>
    <p><a href="http://libr-fantasymania.lebonforum.com/">Libr' FantasYmaniA</a></p>
    <p><a href="http://www.chemins-khatovar.com/forum/viewtopic.php?f=47&t=7184&sid=fcd4853729ba0ccd9d3acd1757d9a23d">Les Chemins de Khatovar</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_facegroups" --></h2>
    <p><a href="https://www.facebook.com/groups/EverythingSciFi.and.Fantasy/search/?query=donjon%20legacy">Everything Sci Fi and Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/1398822120358227/search/?query=donjon%20legacy">Heroic Fantasy et fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/heroicfantasy/search/?query=donjon%20legacy">Heroic Fantasy</a></p>
    <p><a href="https://www.facebook.com/groups/187614501677/search/?query=donjon%20legacy">Fan de Héroïc Fantasy et de fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/1488978857993787/?ref=browser">Fantasy et Science-fiction</a></p>
    <p><a href="https://www.facebook.com/groups/127028880783313/?ref=browser">Science-Fiction-fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/273096772740787/">Séries fantastiques et de science fiction</a></p>
    <p><a href="https://www.facebook.com/groups/205907599559799/">Monde féérique, médiéval et fantastique</a></p>
    <p><a href="https://www.facebook.com/groups/6550919441">Fantasy.fr</a></p>
    <p><a href="https://www.facebook.com/groups/457416327679264">Trolls, Elfes, Lutins, Sorcières, Magiciens, Fauconniers et autres fééries</a></p>
    <p><a href="https://www.facebook.com/groups/Imaginaire2013">Terres de légendes, de fantasy et de l'imaginaire</a></p>
    <p><a href="https://www.facebook.com/groups/noobfans/permalink/1020252138062672/?comment_id=1027556767332209&notif_t=group_comment&notif_id=1460861226151967">NOOB & Co</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_webbroadcasters" --></h2>
    <p><a href="https://www.reddit.com/r/scifi/">Reddit /scifi</a></p>
  </div>

  <div class="col-6 col-12-xsmall">
    <h2><!-- tmpl_var name="text_friends_title_festivals" --></h2>
    <p><a href="https://nice-fictions.fr/">Nice Fictions</a></p>
    <p><a href="http://www.trolls-et-legendes.be">Trolls & Légendes</a></p>
    <p><a href="https://www.salon-fantastique.com/">Salon Fantastique</a></p>
    <p><a href="http://geektouch-festival.com">Geek Touch Festival</a></p>
    <p><a href="http://geek-festival.fr/">Bordeaux Geek Festival</a></p>
    <p><a href="http://www.japan-expo-paris.com/">Japan Expo</a></p>
    <p><a href="http://www.ledormantastique.fr/">Dormantastique</a></p>
    <p><a href="http://www.bajawebfest.com/">Baja Web Fest</a></p>
    <p><a href="http://www.sicilywebfest.com/">Sicily Webfest</a></p>
    <p><a href="https://www.gameinreims.com/">Game in Reims</a></p>
    <p><a href="https://comicconbrussels.com/">Comic Con Brussels</a></p>
  </div>

</div>
</div>

</section>
</div>
</div>
