<div class="container">
  <div class="row hidden-xs">
    <div class="hidden" style="padding-top:30px">
      <a href="index.html"><img src="/images/logo_djl.png" class="img-responsive" style="max-height: 140px; margin: 30px 0;" alt="DonJon Legacy"/></a>
    </div>
    <div class="col-sm-6" style="padding-top:30px">
      <a href="index.html"><img src="/images/logofullmagicbis.png" class="img-responsive main-logo hidden-xs" alt="DonJon Legacy"/></a>
    </div>
    <div class="col-sm-6 text-center" style="color:white; padding-bottom:20px">
      <!-- tmpl_if name="fr-link" -->
      <h2>Next events</h2>
      <div class="row">
      <p class="col-sm-6">20-21 May<br /><a href="http://geek-days.com/">Geek days</a> (Lille)</p>
      <p class="col-sm-6">25-26-27-28 May<br /><a href="http://geek-festival.fr/">Bordeaux Geek Festival</a> (Bordeaux)</p>
      </div>
      <!-- /tmpl_if -->
      <!-- tmpl_if name="en-link" -->
      <h2>Prochains festivals</h2>
      <div class="row">
      <p class="col-sm-6">20-21 Mai<br /><a href="http://geek-days.com/">Geek days</a> (Lille)</p>
      <p class="col-sm-6">25-26-27-28 Mai<br /><a href="http://geek-festival.fr/">Bordeaux Geek Festival</a> (Bordeaux)</p>
      </div>
      <!-- /tmpl_if -->
    </div>
  </div>

