<div class="container">
  <div class="row hidden-xs">
    <div class="col-sm-4" style="padding-top:30px">
      <img src="/images/logo_djl.png" class="img-responsive" style="max-height: 140px; margin: 30px 0;" alt="DonJon Legacy"/>
    </div>
    <div class="col-sm-4" style="padding-top:30px">
      <img src="/images/logo_teignome_magie.png" class="img-responsive center-block main-logo hidden-xs" style="max-height: 200px;" alt="DonJon Legacy"/>
    </div>
    <div class="col-sm-4 text-center" style="color:white; padding-bottom:20px">
      <!-- tmpl_if name="fr-link" -->
      <h2>Next events</h2>
      <p>14-15-16 April<br /><a href="http://www.trolls-et-legendes.be/">Trolls et Légendes</a> (Mons)</p>
      <p>29-30 April<br /><a href="https://nice-fictions.fr/">Nice Fictions</a> (Nice)</p>
      <p>6-7-8 May<br /><a href="https://nice-fictions.fr/">Le Salon Fantastique</a> (Paris)</p>
      <!-- /tmpl_if -->
      <!-- tmpl_if name="en-link" -->
      <h2>Prochains festivals</h2>
      <p>14-15-16 Avril<br /><a href="http://www.trolls-et-legendes.be/">Trolls et Légendes</a> (Mons)</p>
      <p>29-30 Avril<br /><a href="https://nice-fictions.fr/">Nice Fictions</a> (Nice)</p>
      <p>6-7-8 Mai<br /><a href="https://nice-fictions.fr/">Le Salon Fantastique</a> (Paris)</p>
      <!-- /tmpl_if -->
    </div>
  </div>

