<div class="container">
  <div class="row hidden-xs">
    <div class="col-sm-3">
      <img src="/images/logo_djl.png" class="img-responsive" style="max-height: 140px; margin: 30px 0;" alt="DonJon Legacy"/>
    </div>
    <div class="col-sm-6">
      <img src="/images/logo_teignome_magie.png" class="img-responsive center-block main-logo hidden-xs" style="max-height: 200px;" alt="DonJon Legacy"/>
    </div>
    <div class="col-sm-3">
    </div>
  </div>

