<div class="row">

  <div class="col-sm-6">
    <h2><tmpl_var name="text_home_hi" /></h2>
    <p><tmpl_var name="text_home_what" /></p>
    <hr />
    <h2><tmpl_var name="text_home_pitch_title" /></h2>
    <p><tmpl_var name="text_home_pitch" /></p>
    <hr />
    <h2><tmpl_var name="text_home_info" /></h2>
    <p>
        <a class="btn btn-default hvr-bounce-to-right" href="https://twitter.com/DonJon_Legacy"><i class="fa fa-twitter"></i></a>
        <a class="btn btn-default hvr-bounce-to-right" href="https://www.facebook.com/donjonlegacy"><i class="fa fa-facebook"></i></a>
        <a class="btn btn-default hvr-bounce-to-right" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
        <a class="btn btn-default hvr-bounce-to-right" href="http://www.dailymotion.com/donjonlegacy"><i class="fa fa-video-camera"></i></a>
    </p>
  </div>

  <div class="col-sm-6">
    <img src="/images/teignome2.png" alt="teignome" class="img-responsive hvr-buzz" />
  </div>

</div>

<!-- <h2><tmpl_var name="text_home_news" /></h2> -->

<h2><tmpl_var name="text_home_calendar" /></h2>

<ul>
  <li><tmpl_var name="text_home_calendar_201607" /></li>
  <li><tmpl_var name="text_home_calendar_201701" /></li>
</ul>

