<div class="row">

  <div class="col-sm-6">
    <div class="text-center embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/RMXDqLgdjBg" allowfullscreen></iframe>
    </div>
    <div>
    <h2><tmpl_var name="text_home_pitch_title" /></h2>
    <p><tmpl_var name="text_home_pitch" /></p>
    </div>
  </div>

  <div class="col-sm-6">
    <h2><tmpl_var name="text_home_hi" /></h2>
    <p><tmpl_var name="text_home_what" /></p>
    <img src="/images/teignome2.png" alt="teignome" class="img-responsive hvr-buzz center-block" style="max-height: 300px;"/>
  </div>

</div>

<div class="text-center">
  <h2><tmpl_var name="text_home_calendar" /></h2>

  <div class="row">
    <div class="col-sm-5 hidden-xs"></div>
    <div class="col-sm-2 col-xs-6 text-center calendar-date"><h4><tmpl_var name="text_home_calendar_summer" /><br />2016</h4></div>
    <div class="col-sm-5 col-xs-6 text-left calendar-text"><tmpl_var name="text_home_calendar_201607" /></div>
  </div>

  <div class="row">
    <div class="col-sm-5 col-xs-6 text-right calendar-text"><tmpl_var name="text_home_calendar_201701" /></div>
    <div class="col-sm-2 col-xs-6 text-center calendar-date"><h4><tmpl_var name="text_home_calendar_january" /><br />2017</h4></div>
    <div class="col-sm-5 hidden-xs"></div>
  </div>

</div>
