<div class="row">

  <div class="col-sm-6">
    <div class="text-center embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/RMXDqLgdjBg" allowfullscreen></iframe>
    </div>
    <div>
    <h2><tmpl_var name="text_home_pitch_title" /></h2>
    <p><tmpl_var name="text_home_pitch" /></p>
    </div>
  </div>

  <div class="col-sm-6">
    <h2><tmpl_var name="text_home_hi" /></h2>
    <p><tmpl_var name="text_home_what" /></p>
    <img src="/images/teignome2.png" alt="teignome" class="img-responsive hvr-buzz center-block" style="max-height: 300px;"/>
  </div>

</div>
