            <!-- Main -->
                <div id="main" class="wrapper style1 hall">
                    <div class="container">
                        <header class="major">
                            <h2><!-- tmpl_var name="title" --></h2>
                        </header>

                        <!-- Content -->
                            <section id="content">
                                <div class="align-center">
                                    <img src="/images/fighttoread.gif" alt="<!-- tmpl_var name="text_mail_read" -->" class="image" />
                                    <p><!-- tmpl_var name="text_mail_read" --></p>
                                </div>
                            </section>

                    </div>
                </div>
