    <div class="navbar-wrapper">

        <div class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><i class="fa fa-shield hidden-xs"></i><span class="visible-xs">DonJon Legacy</span></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="watch.html"><i class="fa fa-film"></i><!-- tmpl_var name="text_menu_watch" --></a></li>
                <li><a href="hall.html"><i class="fa fa-users"></i><!-- tmpl_var name="text_menu_hall" --></a></li>
                <li><a href="dungeon.html"><i class="fa fa-map-o"></i><!-- tmpl_var name="text_menu_dungeon" --></a></li>
                <li><a href="credits.html"><i class="fa fa-hand-spock-o"></i><!-- tmpl_var name="text_menu_credits" --></a></li>
                <li><a href="contact.html"><i class="fa fa-envelope"></i><!-- tmpl_var name="text_menu_contact" --></a></li>
                <li><a href="press.html"><i class="fa fa-newspaper-o"></i><!-- tmpl_var name="text_menu_press" --></a></li>
                <li><a href="friends.html"><i class="fa fa-heart"></i><!-- tmpl_var name="text_menu_friends" --></a></li>
                <li><a href="awards.html"><i class="fa fa-trophy"></i><!-- tmpl_var name="text_menu_awards" --></a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <!-- tmpl_if name="fr-link" -->
                <li><a href="<!-- tmpl_var name="fr-link" -->"><img src="/images/fr.png" alt="fr" /></a></li>
                <!-- /tmpl_if -->
                <!-- tmpl_if name="en-link" -->
                <li><a href="<!-- tmpl_var name="en-link" -->"><img src="/images/en.png" alt="en" /></a></li>
                <!-- /tmpl_if -->
              </ul>
            </div>
          </div>
        </div>

    </div>

    <div class="row">

        <div class="col-sm-9">

            <div id="content" class="panel panel-default panel-body">
