    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><i class="fa fa-shield hidden-xs"></i><span class="visible-xs">DonJon Legacy</span></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a class="hvr-bounce-to-right" href="watch.html"><i class="fa fa-film"></i><!-- tmpl_var name="text_menu_watch" --></a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
