            <!-- Header -->
                <header id="header">
                    <h1 id="logo"><a href="index.html">DonJon Legacy</a></h1>
                    <nav id="nav">
                        <ul>
                        <li><a href="watch.html"><!-- tmpl_var name="text_menu_watch" --></a></li>
                        <li><a href="hall.html"><!-- tmpl_var name="text_menu_hall" --></a></li>
                        <li><a href="dungeon.html"></i><!-- tmpl_var name="text_menu_dungeon" --></a></li>
                        <li><a href="credits.html"></i><!-- tmpl_var name="text_menu_credits" --></a></li>
                        <li><a href="contact.html"><!-- tmpl_var name="text_menu_contact" --></a></li>
                        <li><a href="press.html"></i><!-- tmpl_var name="text_menu_press" --></a></li>
                        <li><a href="friends.html"></i><!-- tmpl_var name="text_menu_friends" --></a></li>
                        <li><a href="awards.html"></i><!-- tmpl_var name="text_menu_awards" --></a></li>
                        <li><a href="events.html"></i><!-- tmpl_var name="text_menu_events" --></a></li>
                        <!-- tmpl_if name="fr-link" -->
                        <li><a href="<!-- tmpl_var name="fr-link" -->" class="button primary"><img src="/images/fr.png" alt="fr" /></a></li>
                        <!-- /tmpl_if -->
                        <!-- tmpl_if name="en-link" -->
                        <li><a href="<!-- tmpl_var name="en-link" -->" class="button primary"><img src="/images/en.png" alt="en" /></a></li>
                        <!-- /tmpl_if -->
                        </ul>
                    </nav>
                </header>
