<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<div class="text-center">
  <div class="alert alert-djl text-left">
    <!-- tmpl_var name="text_press_intro" -->
  </div>
</div>

<ul>
  <li><a href="http://guilhem0.free.fr/CPDonJonLegacy010117.pdf"><!-- tmpl_var name="text_press_release" --></a></li>
  <li><a href="http://guilhem0.free.fr/dossierPresseDJL.pdf"><!-- tmpl_var name="text_press_pack" --></a></li>
  <li><a href="http://guilhem0.free.fr/KitpressDJL.zip"><!-- tmpl_var name="text_press_kit" --></a></li>
</ul>
