<h1 class="text-center"><!-- tmpl_var name="title" --></h1>

<hr />

<div class="text-center">
  <div class="alert alert-djl text-left">
    <!-- tmpl_var name="text_press_intro" -->
  </div>
</div>

<ul>
  <li><a href="https://drive.google.com/open?id=1Kdge1XqumisMf4Oo51WJsXRJ2fvVn9vs"><!-- tmpl_var name="text_press_release" --></a></li>
  <li><a href="https://drive.google.com/open?id=1T2lQriRoNyN5Bluf0_Xq658Aa9P0oyfo"><!-- tmpl_var name="text_press_pack" --></a></li>
  <li><a href="https://drive.google.com/open?id=1BsIIO4Dr54bFOFqyfTszsgUbH78MdkPk"><!-- tmpl_var name="text_press_kit" --></a></li>
</ul>
