            <!-- Main -->
                <div id="main" class="wrapper style1">
                    <div class="container">
                        <header class="major">
                            <h2>
                                <tmpl_var name="text_watch_channels" />
                                <a href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw" target="_blank" class="text-danger">Youtube</a>
                            </h2>
                        </header>

                        <!-- Content -->
                        <section id="content">
                            <div class="row">
                                <div class="col-4 col-12-xsmall">
                                    <h2><tmpl_var name="text_watch_season" /> 1</h2>
                                    <p><a class="button primary fit" href="https://www.youtube.com/playlist?list=PLMKApLOreTVQzZmzbVQonTA1pVdhyEH_W" target="_blank"><tmpl_var name="text_watch_season1_playlist" /></a></p>
                                    <ul class="alt">
                                        <li><a href="https://www.youtube.com/watch?v=Miaq_E5gmlk" target="_blank"><tmpl_var name="text_watch_s01e01" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=wDuI-ayW3Cw" target="_blank"><tmpl_var name="text_watch_s01e02" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=n-9XF0bcgFw" target="_blank"><tmpl_var name="text_watch_s01e03" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=lvJym9dpBTg" target="_blank"><tmpl_var name="text_watch_s01e04" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=IWlq_RzzDhQ" target="_blank"><tmpl_var name="text_watch_s01e05" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=Mf2x2zzj-vg" target="_blank"><tmpl_var name="text_watch_s01e06" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=LyI6Pe6r0JI" target="_blank"><tmpl_var name="text_watch_s01e07" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=1wJKAFemCVo" target="_blank"><tmpl_var name="text_watch_s01e08" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=Ez6b0CSeBa0" target="_blank"><tmpl_var name="text_watch_s01e09" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=HghgnhyENP0" target="_blank"><tmpl_var name="text_watch_s01ebonus" /></a></li>
                                    </ul>
                                    <p><a class="button fit" href="https://www.youtube.com/watch?v=RMXDqLgdjBg" target="_blank">Teaser</a></p>
                                    <p><a class="button fit" href="https://www.youtube.com/watch?v=1GtwdA92f6U" target="_blank"><tmpl_var name="text_watch_trailer" /></a></p>
                                </div>
                                <div class="col-4 col-12-xsmall">
                                    <h2><tmpl_var name="text_watch_season" /> 2</h2>
                                    <ul class="alt">
                                        <li><a href="https://www.youtube.com/watch?v=rWhaQBglm4k" target="_blank"><tmpl_var name="text_watch_s02e01" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=3Kpat2stI-0" target="_blank"><tmpl_var name="text_watch_s02e02" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=xf03TiTIrgk" target="_blank"><tmpl_var name="text_watch_s02e03" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=awmbm__m4i8" target="_blank"><tmpl_var name="text_watch_s02e04" /></a></li>
                                    </ul>
                                    <p><a class="button fit" href="https://www.youtube.com/watch?v=jThGk9N1nyc" target="_blank">Teaser</a></p>
                                </div>
                                <div class="col-4 col-12-xsmall">
                                    <h2><tmpl_var name="text_watch_special" /></h2>
                                    <ul class="alt">
                                        <li><a href="https://www.youtube.com/watch?v=8dBmxDyn_Dk" target="_blank"><tmpl_var name="text_watch_hse01" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=reK6l5PaVak" target="_blank"><tmpl_var name="text_watch_hse02" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=1qKdPPiyw_8" target="_blank"><tmpl_var name="text_watch_hse03" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=sQoyPOgVBVo" target="_blank"><tmpl_var name="text_watch_hse04" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=ERLI0Lf2ve4" target="_blank"><tmpl_var name="text_watch_hse05" /></a></li>
                                        <li><a href="https://www.youtube.com/watch?v=LiYeuLAcwiY" target="_blank"><tmpl_var name="text_watch_hse06" /></a></li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>
</div>


