<div class="row">

  <h1 class="text-center"><tmpl_var name="title" /></h1>
  <hr />

  <div class="col-sm-6 hidden-xs">
    <img src="/images/teignome4.png" alt="teignome" class="img-responsive hvr-buzz" />
  </div>

  <div class="col-sm-6 col-xs-12">
    <p>
      <tmpl_var name="text_watch_channels" />
      <a class="btn btn-default" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
      <a class="btn btn-default" href="http://www.dailymotion.com/donjonlegacy"><i class="fa fa-video-camera"></i></a>
    </p>
    <h2><tmpl_var name="text_watch_season" /> 1</h2>
    <p><i><tmpl_var name="text_watch_subtitles" /></i></p>
    <ul>
      <li><a href="https://www.youtube.com/watch?v=RMXDqLgdjBg">Teaser (<tmpl_var name="text_watch_201602" />)</a></li>
    </ul>
    <ul>
      <li>Episode 1 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 2 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 3 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 4 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 5 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 6 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 7 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 8 (<tmpl_var name="text_watch_201607" />)</li>
      <li>Episode 9 (<tmpl_var name="text_watch_201607" />)</li>
    </ul>
    <h2><tmpl_var name="text_watch_season" /> 2</h2>
    <p><i><tmpl_var name="text_watch_subtitles" /></i></p>
    <ul>
      <li>Episode 1 (<tmpl_var name="text_watch_201701" />)</li>
    </ul>
  </div>

</div>


