<h1 class="text-center"><tmpl_var name="title" /></h1>
<hr />

<div class="text-center">
  <div class="alert alert-djl">
    <tmpl_var name="text_watch_channels" />
    <a class="btn btn-default" href="https://www.youtube.com/channel/UCVO3scwrW2QEyxiVcBbEbtw"><i class="fa fa-youtube"></i></a>
    <a class="btn btn-default" href="http://www.dailymotion.com/donjonlegacy"><i class="fa fa-video-camera"></i></a>
  </div>
</div>

<div class="row">

  <div class="col-sm-6 hidden-xs">
    <img src="/images/teignome4.png" alt="teignome" class="img-responsive hvr-buzz" />
  </div>

  <div class="col-sm-6 col-xs-12">
    <h2><tmpl_var name="text_watch_season" /> 1</h2>
    <p><i><tmpl_var name="text_watch_subtitles" /></i></p>
    <ul>
      <li><a href="https://www.youtube.com/watch?v=RMXDqLgdjBg">Teaser</a></li>
    </ul>
    <ul>
      <li><a href="https://www.youtube.com/watch?v=1GtwdA92f6U"><tmpl_var name="text_watch_trailer" /></a></li>
    </ul>
    <ul>
      <li><a href="https://www.youtube.com/watch?v=Miaq_E5gmlk"><tmpl_var name="text_watch_s01e01" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=wDuI-ayW3Cw"><tmpl_var name="text_watch_s01e02" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=n-9XF0bcgFw"><tmpl_var name="text_watch_s01e03" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=lvJym9dpBTg"><tmpl_var name="text_watch_s01e04" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=IWlq_RzzDhQ"><tmpl_var name="text_watch_s01e05" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=Mf2x2zzj-vg"><tmpl_var name="text_watch_s01e06" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=LyI6Pe6r0JI"><tmpl_var name="text_watch_s01e07" /></a></li>
      <li><a href="https://www.youtube.com/watch?v=1wJKAFemCVo"><tmpl_var name="text_watch_s01e08" /></a></li>
      <li>Episode 9</li>
    </ul>
    <h2><tmpl_var name="text_watch_season" /> 2</h2>
    <p><i><tmpl_var name="text_watch_subtitles" /></i></p>
    <p><i class="fa fa-clock-o"></i> <tmpl_var name="text_watch_season2" /></p>
  </div>

</div>


